- name: generate_itinerary
  agent: weekend_itinerary_agent
  description: Create a high-level weekend itinerary based on city, interests, and budget
  expected_output: A structured itinerary with time slots, activities, and dining recommendations

- name: suggest_activities
  agent: activity_curator_agent
  description: Recommend personalized activities in the selected city
  expected_output: A list of 5–7 activities with short descriptions, timings, and entry fees if any

- name: recommend_dining
  agent: dining_expert_agent
  description: Find dining options that suit user preferences and stay within budget
  expected_output: A list of restaurants, cafés, or local eateries with cuisine type and estimated cost

- name: provide_local_insights
  agent: local_insights_agent
  description: Offer tips, cultural nuances, and must-know local info for the weekend
  expected_output: Bullet-pointed local insights, dos and don'ts, and safety tips

- name: check_weather
  agent: weather_monitor_agent
  description: Provide the weekend weather forecast for the chosen city
  expected_output: Forecast summary including temperature, rain/sun/cloud, and travel impact notes

- name: plan_transport
  agent: transport_navigator_agent
  description: Suggest optimal local transport options for the planned activities
  expected_output: List of transport modes, estimated time, and cost for each transition between activities

- name: optimize_budget
  agent: budget_advisor_agent
  description: Allocate the total weekend budget efficiently across major categories
  expected_output: Breakdown of budget (e.g., 30% stay, 25% travel, 20% food, etc.) and tips for savings
